# -*- coding: utf-8 -*-
"""PL/EN UI text. Pure data; no Tk or runtime state."""

TR = {
    "pl": {
        "app_title": "ASAonly - (AUTO)Manual - ModRefresher (RCON) (V3.86.7)",
        "api_key": "Klucz API CurseForge:",
        "show": "Pokaz",
        "hide": "Ukryj",
        "check_interval": "Interwał sprawdzania (sek, min 30):",
        "cf_delay": "Opóźnienie między zapytaniami CF (sek):",
        "watch_timeout": "Czuwanie (min):",
        "lang": "EN",
        "lang_btn": "EN/PL",
        "mod_page_btn": "Strona",
        "mod_monitor": "Monitoruj",
        "tab_save": "Zapisz tab",
        "tab_saved": "Zapisano tab '{name}'.",
        "check_now": "Sprawdź mody teraz",
        "add_server": "+ Dodaj mapę",
        "import_ok": "Zaimportowano tab '{name}' z pliku: {file}",
        "import_sec_from": "Hasło RCON podciągnięte z pliku sekretu leżącego obok backupu.",
        "import_sec_legacy": "Hasło RCON pobrane z pliku konfiguracji (stary format backupu).",
        "import_sec_none": "Import bez hasła RCON — uzupełnij je w pluginie RCON.",
        "import_renamed": "Tab '{old}' już istnieje — zaimportowano jako '{new}'.",
        "import_dup_title": "Tab już istnieje",
        "import_dup_ask": "Tab '{name}' już działa w programie — backupy w jego katalogu CONFIG_MAPS_TABS/ i tak są jego własną rotacją.\nImport utworzy DUPLIKAT jako '{new}'.\n\nImportować mimo to?",
        "import_home_note": "Backup z miejsca standardowego — tab przywrócono bez restartu; historia wersji w CONFIG_MAPS_TABS/{dir}/ bez zmian.",
        "import_mods_fixed": "Lista modów z backupu niezgodna z logiem — przyjęto to, co serwer ŁADUJE ({n} modów): {ids}.",
        "import_mods_ok": "Lista modów z backupu zgodna z logiem serwera ({n} modów).",
        "import_mods_unverified": "Serwer nie działa (log milczy) — lista modów z backupu NIE zweryfikowana; sprawdzę ją automatycznie po starcie serwera.",
        "boot_mods_fixed": "[{name}] Serwer wystartował: lista modów skorygowana wg logu ({n} modów): {ids}.",
        "boot_mods_ok": "[{name}] Serwer wystartował: lista modów zweryfikowana — zgodna z logiem ({n} modów).",
        "ip": "IP:",
        "port": "Port RCON:",
        "password": "Hasło RCON:",
        "log_path": "Ścieżka do logów serwera:",
        "browse": "...",
        "status": "Status:",
        "map_active": "Mapa aktywna",
        "stash": "Schowek (komendy)",
        "st_checking": "Sprawdzanie modów...",
        "st_restart": "PROCEDURA RESTARTU",
        "st_next_check": "Następne sprawdzenie: ",
        "st_updated": "Zaktualizowane mody: ",
        "tab_status": "Status mapy: ",
        "tab_last_log": "Ostatni wpis: ",
        "tab_no_log": "(brak ścieżki do logu)",
        "console_hint": "Dziennik zdarzeń widać w tej konsoli; zapis też w WIEDZA_O_PROGRAMIE\\dziennik-zdarzen.txt (ukryte błędy programu: asa_debug.log).",
        "st_starting": "Startuje",
        "st_loading_mods": "Ładuje mody",
        "st_engine": "Silnik gotowy",
        "st_ready": "GOTOWY",
        "st_crash": "CRASH",
        "st_offline": "OFFLINE",
        "st_unknown": "---",
        "tip_map_starting": "Startuje - serwer wstaje, RCON jeszcze nie odpowiada.",
        "tip_map_loading_mods": "Ładuje mody - serwer ładuje mody, chwila czekania.",
        "tip_map_engine": "Silnik gotowy - tuż przed stanem GOTOWY.",
        "tip_map_ready": "GOTOWY - serwer działa, gracze mogą wchodzić.",
        "tip_map_crash": "CRASH - mapa padła; program pilnuje, aż wróci.",
        "tip_map_offline": "OFFLINE - log milczy; serwer nie odpowiada.",
        "tip_map_unknown": "--- - status nieznany; program czeka na dane z logu.",
        "st_monitoring": "Monitoruje",
        "st_pending": "ZALEGŁE UPDATE'Y: ",
        "auto_rcon": "Automat RCON",
        "auto_on_log": "Automat RCON WŁĄCZONY - update'y startują same (kolejna tura 60 s po GOTOWY).",
        "auto_off_log": "Automat RCON WYŁĄCZONY - nowe wykrycia trafią do ZALEGŁOŚCI (nic nie poleci).",
        "pusty_od_razu": "Pusta mapa: restart od razu",
        "pusty_on_log": "Pusta mapa: restart od razu — WŁĄCZONE. Przed restartem program pyta serwer o graczy (ListPlayers); tylko potwierdzony brak graczy pomija ogłoszenia.",
        "pusty_off_log": "Pusta mapa: restart od razu — WYŁĄCZONE. Każda mapa dostaje pełny harmonogram ogłoszeń.",
        "watch_armed": "=== Czuwanie powrotu uzbrojone: {n} map po DoExit. Pilnuję powrotu do GOTOWY. ===",
        "watch_map_ready": "[{name}] GOTOWY ✓ {t} po restarcie.",
        "watch_timeout_map": "[{name}] NIE wrócił po restarcie w ciągu {m} min — sprawdź serwer!",
        "watch_status_fmt": "Czuwanie powrotu: {ready}/{total} GOTOWY",
        "watch_done": "=== Czuwanie powrotu zakończone. ===",
        "watch_park_log": "Update wykryty w trakcie czuwania powrotu — zapisany do zaległości (start po powrocie klastra).",
        "crashloop_log": "[{name}] PRAWDOPODOBNY KRACHLOOP: {n} krachy w {m} min — sprawdź logi / rozważ wycofanie update'a!",
        "sync_btn": "Mody z serwera",
        "sync_log": "Wczytano z folderów serwera {n} modów: {ids} (pole uzupełnione).",
        "sync_log_used": "Serwer ŁADUJE {n} modów (lista z logu): {ids} — to poszło do pola.",
        "sync_log_skip": "Pominięto {n} modów z katalogu (serwer ich NIE ładuje — zostały z testów): {ids}.",
        "sync_log_extra": "Mod z logu bez folderu w katalogu (dodany do listy): {ids}.",
        "sync_log_fallback": "W logu nie znaleziono listy ładowanych modów — wpisano wszystkie {n} z folderów. Jeśli w katalogu jest bajzel z testów, posprzątaj albo sprawdź log.",
        "sync_none_log": "Nie znaleziono folderu modów dla {name}. Szukałem w: {paths}. Jeśli mody masz gdzie indziej, sprawdź Ścieżkę do logów (...\\ShooterGame\\Saved\\Logs).",
        "sync_empty_log": "Folder modów znaleziony, ale nie rozpoznano w nim żadnego moda: {path}.",
        "status_change": "Zmiana statusu [{name}]: {status}",
        "tail_started": "Śledzenie logu [{name}]: {path}",
        "log_tail_err": "Błąd śledzenia logu: ",
        "wykryj_start": "WYKRYJ: skanuję logi i dopasowuję mody (CurseForge).",
        "wykryj_done": "WYKRYJ: sprawdzam {n} map - wyniki w logu i na kafelkach.",
        "nowy_chip": "NOWY",
        "cf_tip_ok": "CurseForge: działa.",
        "cf_tip_blad": "CurseForge: awaria - sonda w rytmie 1/3/15 min.",
        "wykryj": "WYKRYJ",
        "wykryj_tip": "Skanuje logi wszystkich serwerów i dopasowuje mody z CurseForge.",
        "mon_start": "Monitor procesów uruchomiony (skan co 10 s).",
        "mon_blad": "Błąd monitora: {e}",
        "wisi_info": "[{tab}] Cisza w logu od {m} min (autosave co 15 min) - może serwer wisi?",
        "wisi_sonda": "[{tab}] Cisza {m} min - sonda RCON (listplayers, tylko odczyt).",
        "wisi_wrocil": "[{tab}] Log ożył po {m} min ciszy - serwer jednak działa.",
        "sonda_odp": "[{tab}] Sonda: RCON odpowiada - serwer zywy.",
        "sonda_brak": "[{tab}] Sonda bez odpowiedzi - RCON nie żyje razem z logiem.",
        "sonda_blad": "[{tab}] Błąd sondy RCON: ",
        "pad4_start": "[{tab}] Ślad crasha — sprawdzam tożsamość procesu; okno do 90 s (PAD4).",
        "pad4_koniec": "[{tab}] Proces przeżył {s} s po śladzie crasha - to nie PAD (PAD4).",
        "pad_crash": "[{tab}] PAD: proces zniknął po śladzie crasha w logu.",
        "pad_bez_sladu": "[{tab}] PAD: proces zniknął bez śladu crasha (zdechł cicho).",
        "zamkniety_po_doexit": "[{tab}] Serwer zamknięty po DoExit (planowy restart) — czekam, aż wróci.",
        "dl_stuck": "[{tab}] Pobieranie modów przez serwer (CFCore) bez postępu od {m} min - chyba utknęło.",
        "samorestart": "[{tab}] GOTOWY→STARTING bez człowieka - samorestart nr {n} w tej sesji.",
        "auto_kolejna": "GOTOWY - automatycznie kolejna tura za 60 s (anuluj: NASŁUCH wyłączony).",
        "auto_kolejna_stop": "[{tab}] Auto-tura odwołana (NASŁUCH wyłączony).",
        "dziennik_proc": "Przed procedurą: zapis stanu modów do dziennika.",
        "dziennik_ok": "Dziennik: {path}",
        "dziennik_blad": "Dziennik niedostępny: ",
        "cf_sonda_start": "Sonda CF: sprawdzam najmniejszy mod ({mod}) - reszta pewnie też padła.",
        "cf_sonda_ok": "Sonda CF: mod {mod} wrócił po {s} s.",
        "cf_sonda_nie": "Sonda CF: mod {mod} wciąż niedostępny po {s} s - poczekać dłużej.",
        "sonda_chip": "SONDA",
        "wisi_chip": "WISI!",
        "tail_stopped": "Zatrzymano śledzenie logu [{name}]",
        "server_name_title": "Nazwa mapy",
        "server_name_prompt": "Nazwa zakładki:",
        "server_exists": "Taka nazwa już istnieje.",
        "rename_server": "Zmień nazwę zakładki",
        "rename_title": "Zmiana nazwy",
        "rename_prompt": "Nowa nazwa zakładki:",
        "rename_err_empty": "Nazwa nie może być pusta.",
        "rename_ok": "Zakładka \"{old}\" -> \"{new}\".",
        "line_time_invalid": "Czas musi być liczbą całkowitą >= 0.",
        "line_cmd_empty": "Komenda nie może być pusta.",
        "cf_no_key": "Brak klucza API CurseForge.",
        "cf_no_mods": "Brak modów do sprawdzenia (żaden tab nie ma modów albo mapy są wyłączone).",
        "api_from_backup": "Załaduj API z backupu",
        "tt_api_from_backup": "Wskaż stary plik sekretów (CONFIG_SECRET_API - zapis ....json) - klucz API zostanie wczytany do pola powyżej.",
        "api_backup_ok": "Klucz API wczytany z pliku: {file}",
        "api_backup_bad": "W wybranym pliku nie znaleziono klucza API.",
        "api_backup_err": "Nie udało się odczytać pliku (to nie jest poprawny JSON?): {err}",
        "all_files": "Wszystkie pliki",
        "cf_key_gen": "Generator CF-API",
        "tt_cf_key_gen": "Otwiera w przeglądarce stronę generowania klucza API CurseForge (console.curseforge.com/?#/api-keys). Klucz wygenerowany tam wklej w pole obok.",
        "cf_check_start": "Sprawdzanie modów przez CurseForge (Batch Mode)...",
        "cf_update": ">>> Mod {mid} ma nową wersję: {name} {fname}",
        "cf_error": "Mod {mid}: błąd CF: {err}",
        "cf_done": "Sprawdzanie zakończone. Liczba aktualizacji: {n}.",
        "worker_err": "Błąd wewnętrzny sprawdzania (monitoring kontynuuje): ",
        "restart_start": "=== Wykryto update. Start procedury. ===",
        "restart_no_lines": "Brak linii RCON w klastrze — nie można rozpocząć procedury.",
        "restart_line_send": "[{tab}] T+{t}s -> {cmd}",
        "restart_line_err": "[{tab}] Błąd RCON przy T+{t}s (po {r} próbach): {err}",
        "restart_cancel": "Procedura restartu przerwana ręcznie.",
        "restart_already": "Procedura trwa; wykryty update zapisany do zaległości.",
        "cancel_restart": "Anuluj procedurę",
        "btn_mon_mods": "Monitorowane mody",
        "badge_click": "Klik: strona moda na CurseForge",
        "btn_pending_full": "Wykonaj zaległe aktualizacje",
        "save_api": "Zapisz klucz",
        "tt_lang": "Przełącz język interfejsu (polski / angielski).",
        "tt_about": "Informacje o programie: autor, wersja i jak działa.",
        "tt_add_map": "Dodaje nową mapę (serwer). Połączenie i procedurę ustawiasz w wymaganym pluginie RCON.",
        "tt_mods_win": "Otwiera / zamyka okno z kafelkami monitorowanych modów.",
        "tt_plugin_manager": "Otwiera Manager Pluginów: status, ON/OFF, panel i test pluginów użytkowych.",
        "tt_admin_status": "Czy cały program został uruchomiony z prawami administratora Windows. Brak praw może zablokować zapis priority lub affinity.",

        "tt_pending": "Wykonuje od razu zaplanowane aktualizacje modów, które czekają.",
        "tt_cancel": "Anuluje rozpoczętą procedurę restartu / aktualizacji map.",
        "tt_save_api": "Zapisuje TYLKO klucz API do pliku 'CONFIG_SECRET_API - zapis data godzina.json' w katalogu CONFIG_SECRET_API/ obok programu.",
        "tt_show_key": "Pokazuje / ukrywa klucz API.",
        "tt_check_now": "Sprawdza natychmiast w CurseForge, czy mody mają nowe wersje.",
        "tt_api_entry": "Twój prywatny klucz API CurseForge (https://console.curseforge.com/?#/api-keys). Zapis tylko do prywatnego pliku.",
        "tt_interval": "Jak często program ma sprawdzać nowe wersje modów (sekundy).",
        "tt_cf_delay": "Odstęp między paczkami (chunkami) zapytań do CF (sekundy).",
        "tt_watch": "Po restarcie program czuwa tę liczbę minut, zanim uzna mapę za martwą.",
        "tab_secret_saved": "Sekret taba '{name}' zapisany w CONFIG_MAPS_TABS/{dir}/CONFIG_SECRET_RCON/ (plik z datą i godziną zapisu)",
        "secret_migrated": "Tab '{name}': hasło przeniesione z config.json do secrets.json (jednorazowa migracja).",
        "tt_auto": "Automatyczne wysyłanie komend RCON z zaznaczonych linii (bez pytania).",
        "tt_pusty": "Przed restartem program sprawdza graczy (ListPlayers). Potwierdzony brak graczy = bez komunikatów i bez czekania (inne komendy zostają). Niepewność = pełny harmonogram.",
        "guard_skip": "[{tab}] POMINIĘTO '{cmd}' — mapa {status} (serwer nie działa). Mody serwer podniesie sam przy najbliższym starcie.",
        "guard_block_doexit": "[{tab}] WSTRZYMANO DoExit — serwer nie jest GOTOWY ({status}). Mapa wróci do kolejki przy następnym sprawdzeniu CurseForge.",
        "save_ok": "Konfiguracja zapisana.",
        "lang_unsaved_title": "Niezapisane zmiany",
        "lang_unsaved_msg": "Masz niezapisane zmiany (np. mapa bez kliknięcia 'Zapisz tab').\n\nPrzełączyć język i wczytać mapy z dysku?\n\n[Tak = przełącz, niezapisane zmiany przepadną]  [Nie = zostań, nic nie zmieniaj]",
        "unsaved_title": "Niezapisane zmiany",
        "unsaved_msg": "Masz niezapisane zmiany (np. mapa bez kliknięcia 'Zapisz tab').\n\nCo zrobić?",
        "unsaved_btn_save": "Zapisz i zamknij",
        "unsaved_btn_nosave": "Zamknij i nic nie zapisuj",
        "unsaved_btn_stay": "Nie zapisuj i nie zamykaj",
        "secrets_ok": "Klucz API zapisany (plik 'CONFIG_SECRET_API' z datą i godziną zapisu)",
        "save_err": "Błąd zapisu konfiguracji: ",
        "close_warn": "Trwa procedura restartu. Na pewno zamknąć?",
        "crash_detected": "Wykryto nowy plik crashstack.",
        "enable_log_tail": "Monitoruj log na żywo",
        "about_btn": "O programie",
        "about_title": "O programie",
        "about_app_name": "ASAonly - (AUTO)Manual - ModRefresher (RCON)",
        "about_version": "Wersja",
        "about_concept": "Pomysł i koncepcja:",
        "about_concept_name": "@Magus",
        "about_code": "Kod:",
        "about_code_desc": "Arena.ai Agent Mode (do wersji 3.80.35) - asystent, który zamienia pomysł użytkownika w działający kod.",
        "about_code_claude": "Claude (Anthropic) - od wersji 3.81: kolejka restartów, kontrola czasu, pełna wersja angielska, aktualizacja serwera przez SteamCMD i dalsze poprawki.",
        "about_purpose": "Lekki monitor aktualizacji modów ARK: Survival Ascended przez CurseForge API, który w odpowiednim momencie wysyła zaplanowane komendy RCON i oddaje resztę ASA Dedicated Managerowi.",
        "about_free": "Program jest w 100% DARMOWY.",
        "about_joke": "Za próbę zarabiania na nim należy się wielka, tłusta ślina na sweterku. :)",
        "first_run_title": "PIERWSZE URUCHOMIENIE - SZYBKI START",
        "first_run_steps": "Program wykrywa aktualizacje modów i uruchamia\n"
                          "zaplanowaną procedurę RCON. Mody pobiera sam serwer\n"
                          "przez CFCore podczas uruchamiania. Żeby wystartować:\n"
                          "1. Wklej klucz API CurseForge w pole u góry (gwiazdki)\n"
                          "   i kliknij 'Zapisz klucz'. Klucz masz za darmo na:\n"
                          "   https://console.curseforge.com/?#/api-keys\n"
                          "   Masz stary backup programu? Kliknij\n"
                          "   'Załaduj API z backupu' i wskaż plik sekretów.\n"
                          "2. Kliknij '+ Dodaj mapę', potem przycisk 'RCON': IP,\n"
                          "   port i hasło RCON serwera (to NIE jest hasło gracza)\n"
                          "   oraz harmonogram komend -> 'ZAPISZ WSZYSTKIE'.\n"
                          "3. Wskaż folder logu serwera (...Saved/Logs) - stąd\n"
                          "   program czyta status mapy i listę modów.\n"
                          "4. Kliknij 'Mody z serwera' - lista modów wypełni się\n"
                          "   sama tym, co serwer naprawdę ładuje.\n"
                          "5. Kliknij 'Zapisz tab'. Gotowe - program działa.\n"
                          "Szczegóły: pliki README i MANUAL obok programu.\n"
                          "Uwaga: Windows może zapytać o dostęp do folderu -\n"
                          "kliknij 'Zezwól'. Program zapisuje swoje pliki tylko\n"
                          "obok siebie; wskazane logi i rejestr CFCore serwera\n"
                          "wyłącznie odczytuje. Wyjątek: plugin 'Aktualizacja\n"
                          "serwera' instaluje przez SteamCMD nowy build serwera\n"
                          "w jego katalogu (OFF w Managerze Pluginów).",
        "config_warn_title": "UWAGA - logowanie",
        "config_warn": "Ważne: każdy tab (mapa) ma SWÓJ PRYWATNY KATALOG CONFIG_MAPS_TABS/<nazwa>/ obok programu (sekret w osobnym podkatalogu CONFIG_SECRET_RCON/). Pilnuj tych plików.",
        "win_mods_title": "Mody",
        "win_shown": "Okno modów widoczne: {geom}.",
        "tab_mods": "Mody mapy (ID po przecinku):",
        "tile_id": "ID",
        "tile_known": "Marker CF znany",
        "tile_latest": "Marker CF najnowszy",
        "tile_maps": "Mapy",
        "mods_state_ok": "aktualny",
        "mods_state_update": "UPDATE",
        "mods_state_pending": "ZALEGŁY",
        "mods_state_error": "błąd CF",
        "mods_state_checking": "sprawdzam...",
        "mods_state_off": "wył.",
        "mods_state_wait": "nie sprawdzono",
        "mods_no_mods": "Brak modów.\nWczytaj je z serwera w zakładce mapy (przycisk 'Mody z serwera').",
        "restart_skip_map": "[{tab}] pominięto — mapa nie używa zaktualizowanych modów.",

    },
    "en": {
        "app_title": "ASAonly - (AUTO)Manual - ModRefresher (RCON) (V3.86.7)",
        "api_key": "CurseForge API Key:",
        "show": "Show",
        "hide": "Hide",
        "check_interval": "Check interval (sec, min 30):",
        "cf_delay": "Delay between CF batches (sec):",
        "watch_timeout": "Return watch (min):",
        "lang": "PL",
        "lang_btn": "EN/PL",
        "mod_page_btn": "Page",
        "mod_monitor": "Monitor",
        "tab_save": "Save tab",
        "tab_saved": "Tab '{name}' saved.",
        "check_now": "Check mods now",
        "add_server": "+ Add map",
        "import_ok": "Imported tab '{name}' from file: {file}",
        "import_sec_from": "RCON password picked up from the secret file next to the backup.",
        "import_sec_legacy": "RCON password taken from the config file (old backup format).",
        "import_sec_none": "Imported without an RCON password — fill it in the tab.",
        "import_renamed": "Tab '{old}' already exists — imported as '{new}'.",
        "import_dup_title": "Tab already exists",
        "import_dup_ask": "Tab '{name}' is already running — backups in its CONFIG_MAPS_TABS/ directory are its own rotation anyway.\nImporting will create a DUPLICATE as '{new}'.\n\nImport anyway?",
        "import_home_note": "Backup from its standard place — tab restored without a restart; version history in CONFIG_MAPS_TABS/{dir}/ untouched.",
        "import_mods_fixed": "Backup mod list does not match the log — adopted what the server LOADS ({n} mods): {ids}.",
        "import_mods_ok": "Backup mod list matches the server log ({n} mods).",
        "import_mods_unverified": "Server not running (log silent) — backup mod list UNVERIFIED; it will be checked automatically once the server starts.",
        "boot_mods_fixed": "[{name}] Server started: mod list corrected per the log ({n} mods): {ids}.",
        "boot_mods_ok": "[{name}] Server started: mod list verified — matches the log ({n} mods).",
        "ip": "IP:",
        "port": "RCON port:",
        "password": "RCON password:",
        "log_path": "Server log folder:",
        "browse": "...",
        "status": "Status:",
        "map_active": "Map active",
        "stash": "Stash (commands)",
        "st_checking": "Checking mods...",
        "st_restart": "RESTART PROCEDURE",
        "st_next_check": "Next check: ",
        "st_updated": "Updated mods: ",
        "tab_status": "Map status: ",
        "tab_last_log": "Last log entry: ",
        "tab_no_log": "(no log path)",
        "console_hint": "The event log lives in this console and in WIEDZA_O_PROGRAMIE\\dziennik-zdarzen.txt (hidden program errors: asa_debug.log).",
        "st_starting": "Starting",
        "st_loading_mods": "Loading mods",
        "st_engine": "Engine up",
        "st_ready": "READY",
        "st_crash": "CRASH",
        "st_offline": "OFFLINE",
        "st_unknown": "---",
        "tip_map_starting": "Starting - server is coming up, RCON not ready yet.",
        "tip_map_loading_mods": "Loading mods - server is loading mods, hang on.",
        "tip_map_engine": "Engine up - just before READY.",
        "tip_map_crash": "CRASH - the map died; the app watches until it returns.",
        "tip_map_ready": "READY - server is up, players can join.",
        "tip_map_offline": "OFFLINE - log is silent; server not responding.",
        "tip_map_unknown": "--- - status unknown; waiting for log data.",
        "st_monitoring": "Monitoring",
        "st_pending": "PENDING UPDATES: ",
        "auto_rcon": "RCON automation",
        "auto_on_log": "RCON automation ON - updates start on their own (next round 60 s after READY).",
        "auto_off_log": "RCON automation OFF - new detections will be PARKED (nothing fires).",
        "pusty_od_razu": "Empty map: restart at once",
        "pusty_on_log": "Empty map: restart at once — ON. Before a restart the program asks the server for players (ListPlayers); only a confirmed empty server skips the announcements.",
        "pusty_off_log": "Empty map: restart at once — OFF. Every map gets its full announcement schedule.",
        "watch_armed": "=== Return watch armed: {n} map(s) after DoExit. Watching for READY. ===",
        "watch_map_ready": "[{name}] READY ✓ {t} after restart.",
        "watch_timeout_map": "[{name}] did NOT come back within {m} min — check the server!",
        "watch_status_fmt": "Return watch: {ready}/{total} READY",
        "watch_done": "=== Return watch finished. ===",
        "watch_park_log": "Update detected during return watch — saved as pending (start after cluster is READY).",
        "crashloop_log": "[{name}] LIKELY CRASH LOOP: {n} crashes in {m} min — check logs / consider rolling back the update!",
        "sync_btn": "Mods from server",
        "sync_log": "Read {n} mods from server folders: {ids} (field filled).",
        "sync_log_used": "The server LOADS {n} mods (list from the log): {ids} — that is what went into the field.",
        "sync_log_skip": "Skipped {n} mods from the directory (the server does NOT load them — leftovers from testing): {ids}.",
        "sync_log_extra": "Mod present in the log but with no folder (added to the list): {ids}.",
        "sync_log_fallback": "No loaded-mods list found in the log — filled in all {n} from the folders. If the directory is a mess from testing, clean it up or check the log.",
        "sync_none_log": "No mods folder found for {name}. Looked in: {paths}. If your mods live elsewhere, fix the Server log path (...\\ShooterGame\\Saved\\Logs).",
        "sync_empty_log": "Mods folder found but no recognizable mods inside: {path}.",
        "status_change": "Status change [{name}]: {status}",
        "tail_started": "Log tailing started [{name}]: {path}",
        "log_tail_err": "Log tail error: ",
        "wykryj_start": "DETECT: scanning logs and matching mods (CurseForge).",
        "wykryj_done": "DETECT: checking {n} maps - results in the log and on the tiles.",
        "nowy_chip": "NEW",
        "cf_tip_ok": "CurseForge: up.",
        "cf_tip_blad": "CurseForge: down - probing at 1/3/15 min cadence.",
        "wykryj": "DETECT",
        "wykryj_tip": "Scans all server logs and matches mods against CurseForge.",
        "mon_start": "Process monitor started (scan every 10 s).",
        "mon_blad": "Monitor error: {e}",
        "wisi_info": "[{tab}] Log silent for {m} min (autosave every 15 min) - server hang?",
        "wisi_sonda": "[{tab}] {m} min silent - RCON probe (listplayers, read-only).",
        "wisi_wrocil": "[{tab}] Log alive again after {m} min of silence - server is fine.",
        "sonda_odp": "[{tab}] Probe: RCON answers - server alive.",
        "sonda_brak": "[{tab}] Probe got no answer - RCON dead along with the log.",
        "sonda_blad": "[{tab}] RCON probe error: ",
        "pad4_start": "[{tab}] Crash trace — checking process identity; up to 90 s window (PAD4).",
        "pad4_koniec": "[{tab}] Process survived {s} s after crash trace - not a PAD (PAD4).",
        "pad_crash": "[{tab}] PAD: process gone after a crash trace in the log.",
        "pad_bez_sladu": "[{tab}] PAD: process gone with no crash trace (died quietly).",
        "zamkniety_po_doexit": "[{tab}] Server closed after DoExit (planned restart) — waiting for it to come back.",
        "dl_stuck": "[{tab}] Server mod download (CFCore) with no progress for {m} min - looks stuck.",
        "samorestart": "[{tab}] READY→STARTING with no human - auto-restart no. {n} this session.",
        "auto_kolejna": "READY - next round automatically in 60 s (cancel: WATCH off).",
        "auto_kolejna_stop": "[{tab}] Auto round cancelled (WATCH off).",
        "dziennik_proc": "Before procedure: saving mod state to the journal.",
        "dziennik_ok": "Journal: {path}",
        "dziennik_blad": "Journal unavailable: ",
        "cf_sonda_start": "CF probe: checking the smallest mod ({mod}) - the rest likely fell too.",
        "cf_sonda_ok": "CF probe: mod {mod} back after {s} s.",
        "cf_sonda_nie": "CF probe: mod {mod} still down after {s} s - wait longer.",
        "sonda_chip": "PROBE",
        "wisi_chip": "HANG!",
        "tail_stopped": "Log tailing stopped [{name}]",
        "server_name_title": "Map name",
        "server_name_prompt": "Tab name:",
        "server_exists": "A tab with that name already exists.",
        "rename_server": "Rename tab",
        "rename_title": "Rename",
        "rename_prompt": "New tab name:",
        "rename_err_empty": "Name cannot be empty.",
        "rename_ok": "Tab \"{old}\" -> \"{new}\".",
        "line_time_invalid": "Time must be an integer >= 0.",
        "line_cmd_empty": "Command cannot be empty.",
        "cf_no_key": "Missing CurseForge API key.",
        "cf_no_mods": "No mods to check (no tab has mods, or maps are disabled).",
        "api_from_backup": "Load API from backup",
        "tt_api_from_backup": "Point to an old secrets file (CONFIG_SECRET_API - zapis ....json) - the API key will be loaded into the field above.",
        "api_backup_ok": "API key loaded from file: {file}",
        "api_backup_bad": "No API key found in the selected file.",
        "api_backup_err": "Could not read the file (not valid JSON?): {err}",
        "all_files": "All files",
        "cf_key_gen": "CF-API generator",
        "tt_cf_key_gen": "Opens the CurseForge API key page (console.curseforge.com/?#/api-keys) in your browser. Generate the key there and paste it into the field next to it.",
        "cf_check_start": "Checking mods via CurseForge (Batch Mode)...",
        "cf_update": ">>> Mod {mid} has an update: {name} {fname}",
        "cf_error": "Mod {mid}: CF error: {err}",
        "cf_done": "Check complete. Updates: {n}.",
        "worker_err": "Internal check error (monitoring continues): ",
        "restart_start": "=== Update detected. Starting procedure. ===",
        "restart_no_lines": "No RCON lines in cluster - cannot start procedure.",
        "restart_line_send": "[{tab}] T+{t}s -> {cmd}",
        "restart_line_err": "[{tab}] RCON error at T+{t}s (after {r} retries): {err}",
        "restart_cancel": "Restart procedure cancelled manually.",
        "restart_already": "Procedure running; detected update saved as pending.",
        "cancel_restart": "Cancel procedure",
        "btn_mon_mods": "Monitored mods",
        "badge_click": "Click: mod page on CurseForge",
        "btn_pending_full": "Run pending updates",
        "save_api": "Save key",
        "tt_lang": "Switch interface language (Polish / English).",
        "tt_about": "About this program: author, version and how it works.",
        "tt_add_map": "Adds a new map (server). Configure its connection and procedure in the required RCON plugin.",
        "tt_mods_win": "Opens / closes the tile window of monitored mods.",
        "tt_plugin_manager": "Opens Plugin Manager: status, ON/OFF, panel and user-plugin tests.",

        "tt_pending": "Runs the pending mod updates immediately.",
        "tt_cancel": "Cancels the running restart / update procedure.",
        "tt_save_api": "Saves ONLY the API key to the timestamped 'CONFIG_SECRET_API' file in the CONFIG_SECRET_API/ directory next to the program.",
        "tt_show_key": "Shows / hides the API key.",
        "tt_check_now": "Immediately checks CurseForge for newer mod versions.",
        "tt_api_entry": "Your private CurseForge API key (https://console.curseforge.com/?#/api-keys). Saved only to the private file.",
        "tt_interval": "How often the program checks for new mod versions (seconds).",
        "tt_cf_delay": "Delay between CurseForge API chunks (seconds).",
        "tt_watch": "After a restart the program watches this many minutes before declaring a map dead.",
        "tab_secret_saved": "Tab secret for '{name}' saved in CONFIG_MAPS_TABS/{dir}/CONFIG_SECRET_RCON/ (timestamped file)",
        "secret_migrated": "Tab '{name}': password moved from config.json to secrets.json (one-time migration).",
        "tt_auto": "Automatic RCON sending of the ticked lines (without asking).",
        "tt_admin_status": "Whether the whole program runs with Windows administrator rights. Without them writing priority or affinity may be blocked.",
        "tt_pusty": "Before a restart the program checks for players (ListPlayers). A confirmed empty server = no messages and no waiting (other commands stay). Uncertainty = full schedule.",
        "guard_skip": "[{tab}] SKIPPED '{cmd}' - map is {status} (server is down). The server will update its mods by itself on its next start.",
        "guard_block_doexit": "[{tab}] DoExit HELD - server is not READY ({status}). The map returns to the queue at the next CurseForge check.",
        "save_ok": "Configuration saved.",
        "lang_unsaved_title": "Unsaved changes",
        "lang_unsaved_msg": "You have unsaved changes (e.g. a map without clicking 'Save tab').\n\nSwitch language and reload maps from disk?\n\n[Yes = switch, unsaved changes will be lost]  [No = stay, change nothing]",
        "unsaved_title": "Unsaved changes",
        "unsaved_msg": "You have unsaved changes (e.g. a map without clicking 'Save tab').\n\nWhat to do?",
        "unsaved_btn_save": "Save and close",
        "unsaved_btn_nosave": "Close without saving",
        "unsaved_btn_stay": "Don't save, don't close",
        "secrets_ok": "API key saved (timestamped 'CONFIG_SECRET_API' file)",
        "save_err": "Config save error: ",
        "close_warn": "A restart procedure is running. Really quit?",
        "crash_detected": "New crashstack file detected.",
        "enable_log_tail": "Tail live log",
        "about_btn": "About",
        "about_title": "About",
        "about_app_name": "ASAonly - (AUTO)Manual - ModRefresher (RCON)",
        "about_version": "Version",
        "about_concept": "Idea & concept:",
        "about_concept_name": "@Magus",
        "about_code": "Code:",
        "about_code_desc": "Arena.ai Agent Mode (up to version 3.80.35) - an assistant that turns a user's idea into working code.",
        "about_code_claude": "Claude (Anthropic) - since version 3.81: the restart queue, the time check, the complete English version, the server update via SteamCMD and further fixes.",
        "about_purpose": "Lightweight ARK: Survival Ascended mod update monitor via the CurseForge API. When the time comes, it sends your scheduled RCON commands and leaves the rest to ASA Dedicated Manager.",
        "about_free": "This program is 100% FREE.",
        "about_joke": "Trying to make money on it deserves a big fat spit on your sweater. :)",
        "first_run_title": "FIRST RUN - QUICK START",
        "first_run_steps": "The program detects mod updates and runs your\n"
                          "scheduled RCON procedure. The server itself downloads\n"
                          "mods through CFCore during startup. To start:\n"
                          "1. Paste your CurseForge API key into the top field\n"
                          "   (asterisks) and click 'Save key'. Free key at:\n"
                          "   https://console.curseforge.com/?#/api-keys\n"
                          "   Have an old program backup? Click 'Load API from\n"
                          "   backup' and point to the secrets file.\n"
                          "2. Click '+ Add map', then the 'RCON' button: the\n"
                          "   server's IP, RCON port and RCON password (NOT a\n"
                          "   player one) and the command schedule -> 'SAVE ALL'.\n"
                          "3. Point to the server's log folder (...Saved/Logs)\n"
                          "   - map status and the mod list are read from it.\n"
                          "4. Click 'Mods from server' - the list fills itself\n"
                          "   with what the server really loads.\n"
                          "5. Click 'Save tab'. Done - the program is live.\n"
                          "Details: README and MANUAL files next to the\n"
                          "program.\n"
                          "Note: Windows may ask about folder access - click\n"
                          "'Allow'. It writes its own files only next to itself;\n"
                          "configured server logs and the CFCore registry are\n"
                          "read-only. Exception: the 'Server update' plugin\n"
                          "installs new server builds with SteamCMD in the\n"
                          "server folder (OFF in the Plugin Manager).",
        "config_warn_title": "WARNING - file with passwords and key",
        "config_warn": "Important - login data: every tab (map) has its OWN PRIVATE DIRECTORY CONFIG_MAPS_TABS/<name>/ next to the program (secret in its own CONFIG_SECRET_RCON/ subdirectory).",
        "win_mods_title": "Mods",
        "win_shown": "Mods window shown: {geom}.",
        "tab_mods": "Map mods (comma-separated IDs):",
        "tile_id": "ID",
        "tile_known": "Known CF marker",
        "tile_latest": "Latest CF marker",
        "tile_maps": "Maps",
        "mods_state_ok": "up to date",
        "mods_state_update": "UPDATE",
        "mods_state_pending": "PENDING",
        "mods_state_error": "CF error",
        "mods_state_checking": "checking...",
        "mods_state_off": "off",
        "mods_state_wait": "not checked yet",
        "mods_no_mods": "No mods.\nLoad them from the server in a map tab ('Mods from server' button).",
        "restart_skip_map": "[{tab}] skipped - map does not use updated mods.",

    },
}

